---
- name: cisco
  hosts: all
  gather_facts: no
  connection: local


  tasks:
    - name: show_output
      ios_command:
        commands:
          - show version
      register: show

    - name: Make Result Directory
      local_action:
        module: file
        path: "/var/lib/awx/projects/Backup/{{ lookup('pipe', 'date +%Y%m%d') }}"
        state: directory
        mode: u=rwX,g=rX,o=rX

    - name: show_backup
      local_action:
        copy content="{{ show.stdout[1] }}"
        dest=/var/lib/awx/projects/Backup/{{ lookup('pipe', 'date +%Y%m%d') }}/TEST.txt
