---
- name: cisco
  hosts: ios
  gather_facts: no
  connection: local


  tasks:
    - name: show_output
      ios_command:
        commands:
          - show version
      register: show

    - name: show_backup
      become: no
      local_action:
        copy content="{{ show.stdout[1] }}"
        dest=/var/lib/awx/projects/_46__test3/{{ inventory_hostname }}.txt
