---
- name: cisco
  hosts: all
  gather_facts: no
  connection: local


  tasks:
    - name: show_output
      ios_command:
        commands:
          - show version
      register: show

    - name: Make Result Directory
      local_action:
        module: file
        path: "Backup/{{ lookup('pipe', 'date +%Y%m%d') }}"
        state: directory
        mode: u=rwX,g=rX,o=rX

    - name: show_backup
      local_action:
        copy content="\n\nshow run\n\n{{show.stdout[1] }}"
        dest=Backup/{{ lookup('pipe', 'date +%Y%m%d') }}/{{ inventory_hostname }}.txt
